mod hello;
mod add;
mod vector;
mod bool;
mod ownership;
mod borrowing;
mod mutable_ref;
// mod struct_and_impl;
mod _impl;
mod tuple;
mod refrence;
mod array;
mod shadowing;
mod for_loop;
mod mat_ch;
mod input_in_rust;
mod enum_with_values;
mod defined_enums;
fn main() {
   hello::say_hello();
   add::add(4, 5);
   bool::is_even(3);
   vector::vector();
   ownership::string();
   borrowing::string();
   borrowing::string1();
   mutable_ref::print();
   _impl::give_pbh(2, 3, 4);
   tuple::tuple();
   refrence::reference();
   array::arr();
   shadowing::shadow();
   for_loop::for_loop();
   mat_ch::mat_ch();
   input_in_rust::mat_ch();
   enum_with_values::enum_with_val();
   defined_enums::defined_enums();
}
